### ISSUE TITLE
🐞 [Bug Report] - Cold Starts - Resolve long load time for / and /site-config routes

### ISSUE THREAD

**Issue by pattishin** [GoogleCloudPlatform/avocano#74]
**Describe the bug**

Resolve long initial load time. (Possible this is the service worker's doing).

Quote from @grayside 
"Showing a blocking, 9 second cold-start for site_config/, and no fast paint with cached assets to bridge the gap if the site was previously visited. Inserted a dev tools screenshot."

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by glasnt** [comment]
The `get_service_url()` method that self-interrogates for the service URL could be part of the issue. 

As @muncus suggested, with tracing now in place, we should be able to debug this further.

**Comment by grayside** [comment]
Additional avenues raised in discussion:

* Add a post-deploy curl to "pre-warm" the Cloud Run service. https://github.com/GoogleCloudPlatform/terraform-dynamic-python-webapp/pull/42 @glasnt 
* Check if healthcheck is introducing startup delays @wietsevenema via @glasnt
* Check if CPU/Memory resource starvation is a problem @grayside 
* Implement a "performance UX" mitigation in painting as much of the page as possible without Cloud Run, and asynchronously updating/filling in the page once Cloud Run response becomes available @grayside

**Comment by pattishin** [comment]
For the latter point, to help with the UI side of this - added a overall loading page to that will wait till config from `/site_config` is present. (PR: https://github.com/GoogleCloudPlatform/avocano/pull/155)

**Comment by grayside** [comment]
Based on the line of work in https://github.com/GoogleCloudPlatform/terraform-dynamic-python-webapp/pull/66, we may be back to considering 7-9 second cold starts here.

**Comment by glasnt** [comment]
The startup probe was removed in #225, but further investigations show that the default period of 10s was a larger issue than the probe at all. 

This could be re-introduced with a period of 1s, to avoid the bitrot of unused healthcheck code.

**Comment by grayside** [comment]
We should probably address bringing back a reasonable healthcheck in a follow-up issue. This seems like it should go back to original scope: can we reduce the ~8 second cold start?

**Comment by glasnt** [comment]
General notes: "warm time" is the time it takes a warm instance to respond to an API call. "cold times" are the first call post a new or old cloud run instance. 

Testing for each iteration was to update the service with a noop configuration change, sleep a moment so the new revision would be configured to serve all traffic, then call a data-ful endpoint 3 times (`/api/active/products/`). The first call would be 'cold', the second and third 'warm'. This would be repeated 3 - 4 times and a general average gathered.

```
gcloud run services update SERVICE --region us-central1 --update-env-vars BEEP=boop \
  && sleep 5 \
  && date && time curl ENDPOINT -I \
  && date && time curl ENDPOINT -I \
  && date && time curl ENDPOINT -I
```

Generally, all warm times in all setups was ~1.0 - 1.5 seconds.
With current configurations, "cold time" is ~7 - 8s, per earlier comments, and using the above method, ~9-12s. 

Investigation summary: 

Application is not CPU/Mem bound

* Running application through Cloud Shell, using Cloud Run Proxy, the cold start time was within ~0.5s of warm time. 
  * This environment has 16GB memory, 4 CPUs (reports `htop`). 
* Increasing Cloud Run resources to 16GB memory, 4CPUs *did not* improve performance.  

Cloud Run's provided proxy to Cloud SQL does not inhibit performance

* Running the same tests on the [cloud sql/cloud run flask/sqlalchemy](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/audit_storage_handler/cloud-sql/postgres/sqlalchemy) sample, the configurations that used the Cloud SQL connectors were not significantly faster than using Cloud SQL proxy. 'cold' start times were 3-5s in both versions, with default server specs. 

There are some efficiency improvements possible for the server code

* Using Adam Johnson's [Django profiling](https://adamj.eu/tech/2023/03/02/django-profile-and-improve-import-time) blogpost, I was able to identify using `importtime-waterfall` on my local machine, that the import times for django and drf serialisers were complex, but also the cloudrun_helpers was potentially able to be tuned. 
* Tests were also performed on different python versions, but given the lack of built packages for 3.12 versions of grpcio and 
psycopg2-binary, only 3.9, 3.10 and 3.11 were tested, The difference was negligible, and avocano already runs 3.11. 

Removing `opentelemetry-instrument` would improve performance, but at the cost of functionality

* Removing this executable from the `Procfile` did allow for ~4s startups, but would remove the telemetry functionality
* Work could be done to add this more manually rather than using autodiscovery, which may improve performance.

---

The cloudrun_helpers.py file is used to self-interrogate the Cloud Run service URL on Django settings load (on cold start), rather than have the URL be encoded as an environment variable. This value is used for CSRF settings. 

The method currently used uses `httpx` for URL calls, and `googleapidiscovery` for Cloud Run API calls. `urllib3` is already used by `gooogle-auth`, and httpx was showing up as being a bit complex, but I thought the main issue was the lag time initialising the run api through `build`. This pathway wasn't being run in a Cloud Shell setting, so would have been skipped in those tests. 

https://github.com/GoogleCloudPlatform/avocano/pull/295 attempts to remove the googleapidiscovery and httpx dependencies, and drop down to pure urllib3. Small issue is urlllib3 recently hit 2.0 and has some API shape changes, and google-auth still uses 1.x. These are noted inline in the code. 

---

Deployment currently active on avocano-preview (cart) environment shows cold boots down to ~2-3 seconds. This is faster than the flask/sqlalchemy test, which is concerning, but it's relatively faster than earlier observations. 

Initial comparison tests on avocano-preview-basic showed _even faster_, but that environment currently has #294 deployed. Deploying main avocano to that env and trying again, and it's still *too* fast. 

I can't see any settings like min instances on these environments that would case it to be very fast, it might be an idea to re-create these environments, or test this on a new project to confirm.

**Comment by glasnt** [comment]
Changes in https://github.com/GoogleCloudPlatform/avocano/pull/307 may resolve more than the other changes in here. 

In that PR, it's observed that the startup probe dropped from 8 checks to 4 checks. Each check a period of 1 second. 

Observations on avocano project show startup probes going from an average of 9.2s (N=12), to 5.8s (N=21)

Observations on avocano-cart project show startup probes going from an average of 8.1s (N=27), to 5.12s (N=13)

**Comment by grayside** [comment]
This is fantastic progress and it's clear there's not further optimization opportunities without making deeper architectural changes. Thank you for multiple rounds of investigation and improvement.
